---
blank_issues_enabled: true
contact_links:
  - name: Discord server
    about: Join our Discord server for support and discussion.
    url: https://the-dont-be-evil-company.com/discord
  - name: Roadmap
    about: View the project roadmap and upcoming features.
    url: https://the-dont-be-evil-company.com/roadmap?filter=kulala.nvim
